### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by LecrisUT**
According to the [documentation](https://plugins.jetbrains.com/docs/intellij/api-changes-list-2022.html) when targeting 2022.2+, the plugin should use Java17. This PR bumps the java, kotlin and other dependencies. Will add another PR that resolves various of the deprecation issues

### CODE REVIEW

**Comment by satamas** [comment]
I am really sorry that I missed your pull requests. I applied all changes from it that were not made by me already independently

**Comment by LecrisUT** [comment]
Thanks for coming back to this. I want to get the CI working on this and get a structure more similar to rust, then I can help with some long-standing bugs. But I need some help on that, and I can't get any advice from the rust plugin team. Do you think you can ping someone over there?

**Comment by satamas** [comment]
I will ping them. We were also copying the rust plugin structure during the plugin development, I suppose that it just changed over time.

**Comment by LecrisUT** [comment]
Indeed it has changed. [Here](https://github.com/intellij-rust/intellij-rust/discussions/10597) is the discussion I had opened for advice, and the structure I am interested is like:
```kotlin
project(":plugin") {
  // Main plugin definitions
}
project(":idea") {
  // Wrapper for idea specific
}
project(":clion") {
  // Wrapper for clion specific
}
project(":other_plugin_support") {
}
```

**Pull request closed without merging**
